services:
  database:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/project
    container_name: my_spring_backend
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/SyncPlanner
      dockerfile: Dockerfile
    container_name: my_angular_frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  postgres_data:
